// Generated by CoffeeScript 1.3.3
(function() {
  var Watcher,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  Watcher = (function() {

    function Watcher(form, options) {
      var Decorator, Validator, hiddenSubmitButtonElement, submitButtons, _i, _j, _len, _len1, _ref, _ref1, _ref2,
        _this = this;
      this.form = typeof form === "string" ? $("#" + form) : $(form);
      if (this.form.length < 1) {
        throw "Form element not found.";
      } else if (this.form.length > 1) {
        throw "More than one form was found.";
      } else if (this.form.get(0).nodeName !== "FORM") {
        throw "The element was not a form.";
      }
      this.allElements = [];
      this.id = Formwatcher.currentWatcherId++;
      Formwatcher.add(this);
      this.observers = {};
      this.form.fwData("watcher", this);
      this.form.fwData("originalAction", this.form.attr("action") || "").attr("action", "javascript:undefined;");
      this.options = Formwatcher.deepExtend({}, Formwatcher.defaultOptions, options || {});
      this.decorators = [];
      this.validators = [];
      _ref = Formwatcher.decorators;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        Decorator = _ref[_i];
        this.decorators.push(new Decorator(this));
      }
      _ref1 = Formwatcher.validators;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        Validator = _ref1[_j];
        this.validators.push(new Validator(this));
      }
      if (this.options.ajaxMethod === null) {
        this.options.ajaxMethod = (_ref2 = this.form.attr("method")) != null ? _ref2.toLowerCase() : void 0;
      }
      switch (this.options.ajaxMethod) {
        case "post":
        case "put":
        case "delete":
          break;
        default:
          this.options.ajaxMethod = "get";
      }
      this.observe("submit", this.options.onSubmit);
      this.observe("success", this.options.onSuccess);
      this.observe("error", this.options.onError);
      this.observe("complete", this.options.onComplete);
      $(inputSelector, this.form).each(function(input) {
        var element, elements, errorsElement, i, label, onchangeFunction, validateElementsFunction, validator, _k, _len2, _ref3, _results;
        input = $(input);
        if (!input.fwData("initialized")) {
          if (input.attr("type") === "hidden") {
            return input.fwData("forceSubmission", true);
          } else {
            elements = Formwatcher.decorate(_this, input);
            if (elements.input.get() !== input.get()) {
              elements.input.attr("class", input.attr("class"));
              input = elements.input;
            }
            if (!elements.label) {
              label = Formwatcher.getLabel(elements, _this.options.automatchLabel);
              if (label) {
                elements.label = label;
              }
            }
            if (!elements.errors) {
              errorsElement = Formwatcher.getErrorsElement(elements, true);
              elements.errors = errorsElement;
            }
            _this.allElements.push(elements);
            input.fwData("validators", []);
            _ref3 = _this.validators;
            for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
              validator = _ref3[_k];
              if (validator.accepts(input, _this)) {
                Formwatcher.debug("Validator \"" + validator.name + "\" found for input field \"" + input.attr("name") + "\".");
                input.fwData("validators").push(validator);
              }
            }
            Formwatcher.storeInitialValue(elements);
            if (input.val() === null || !input.val()) {
              for (i in elements) {
                element = elements[i];
                element.addClass("empty");
              }
            }
            if (!_this.options.submitUnchanged) {
              Formwatcher.removeName(elements);
            }
            onchangeFunction = function() {
              return Formwatcher.changed(elements, _this);
            };
            validateElementsFunction = function() {
              return _this.validateElements(elements, true);
            };
            _results = [];
            for (i in elements) {
              element = elements[i];
              _results.push((function(element) {
                var _this = this;
                element.on("focus", function() {
                  return element.addClass("focus");
                });
                element.on("blur", function() {
                  return element.removeClass("focus");
                });
                element.on("change", onchangeFunction);
                element.on("blur", onchangeFunction);
                return element.on("keyup", validateElementsFunction);
              })(element));
            }
            return _results;
          }
        }
      });
      submitButtons = $("input[type=submit], button[type=''], button[type='submit'], button:not([type])", this.form);
      hiddenSubmitButtonElement = $.create('<input type="hidden" name="" value="" />');
      this.form.append(hiddenSubmitButtonElement);
      submitButtons.each(function(element) {
        element = $(element);
        return element.click(function(e) {
          var elementValue, tmpElementText, _ref3, _ref4;
          if (element[0].tagName === "BUTTON") {
            tmpElementText = element.text();
            element.text("");
            elementValue = (_ref3 = element.val()) != null ? _ref3 : "";
            element.text(tmpElementText);
          } else {
            elementValue = (_ref4 = element.val()) != null ? _ref4 : "";
          }
          hiddenSubmitButtonElement.attr("name", element.attr("name") || "").val(elementValue);
          _this.submitForm();
          return e.stopPropagation();
        });
      });
    }

    Watcher.prototype.callObservers = function() {
      var args, eventName, observer, _i, _len, _ref, _results;
      eventName = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      _ref = this.observers[eventName];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer.apply(this, args));
      }
      return _results;
    };

    Watcher.prototype.observe = function(eventName, func) {
      if (this.observers[eventName] === undefined) {
        this.observers[eventName] = [];
      }
      this.observers[eventName].push(func);
      return this;
    };

    Watcher.prototype.stopObserving = function(eventName, func) {
      var observer;
      this.observers[eventName] = (function() {
        var _i, _len, _ref, _results;
        _ref = this.observers[eventName];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          observer = _ref[_i];
          if (observer !== func) {
            _results.push(observer);
          }
        }
        return _results;
      }).call(this);
      return this;
    };

    Watcher.prototype.enableForm = function() {
      return $(inputSelector, this.form).removeAttr("disabled");
    };

    Watcher.prototype.disableForm = function() {
      return $(inputSelector, this.form).attr("disabled", "disabled");
    };

    Watcher.prototype.submitForm = function(e) {
      var _this = this;
      if (!this.options.validate || this.validateForm()) {
        this.callObservers("submit");
        this.form.addClass("submitting");
        if (this.options.ajax) {
          this.disableForm();
          return this.submitAjax();
        } else {
          this.form.attr("action", this.form.fwData("originalAction"));
          setTimeout(function() {
            _this.form.submit();
            return _this.disableForm();
          }, 1);
          return false;
        }
      }
    };

    Watcher.prototype.validateForm = function() {
      var elements, validated, _i, _len, _ref;
      validated = true;
      _ref = this.allElements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elements = _ref[_i];
        if (!this.validateElements(elements)) {
          validated = false;
        }
      }
      return validated;
    };

    Watcher.prototype.validateElements = function(elements, inlineValidating) {
      var element, i, input, sanitizedValue, validated, validationOutput, validator, _i, _j, _len, _len1, _ref, _ref1;
      input = elements.input;
      validated = true;
      if (input.fwData("validators").length) {
        if (!inlineValidating || !input.fwData("lastValidatedValue") || input.fwData("lastValidatedValue") !== input.val()) {
          input.fwData("lastValidatedValue", input.val());
          Formwatcher.debug("Validating input " + input.attr("name"));
          input.fwData("validationErrors", []);
          _ref = input.fwData("validators");
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            validator = _ref[_i];
            if (input.val() === "" && validator.name !== "Required") {
              Formwatcher.debug("Validating " + validator.name + ". Field was empty so continuing.");
              continue;
            }
            Formwatcher.debug("Validating " + validator.name);
            validationOutput = validator.validate(validator.sanitize(input.val()), input);
            if (validationOutput !== true) {
              validated = false;
              input.fwData("validationErrors").push(validationOutput);
              break;
            }
          }
          if (validated) {
            elements.errors.html("").hide();
            for (i in elements) {
              if (!__hasProp.call(elements, i)) continue;
              element = elements[i];
              element.addClass("validated");
              element.removeClass("error");
            }
            if (inlineValidating) {
              elements.input.fwData("forceValidationOnChange", true);
            }
          } else {
            for (i in elements) {
              if (!__hasProp.call(elements, i)) continue;
              element = elements[i];
              element.removeClass("validated");
            }
            if (!inlineValidating) {
              elements.errors.html(input.fwData("validationErrors").join("<br />")).show();
              for (i in elements) {
                if (!__hasProp.call(elements, i)) continue;
                element = elements[i];
                element.addClass("error");
              }
            }
          }
        }
        if (!inlineValidating && validated) {
          sanitizedValue = input.fwData("lastValidatedValue");
          _ref1 = input.fwData("validators");
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            validator = _ref1[_j];
            sanitizedValue = validator.sanitize(sanitizedValue);
          }
          input.val(sanitizedValue);
        }
      } else {
        for (i in elements) {
          if (!__hasProp.call(elements, i)) continue;
          element = elements[i];
          element.addClass("validated");
        }
      }
      return validated;
    };

    Watcher.prototype.submitAjax = function() {
      var fieldCount, fields, i,
        _this = this;
      Formwatcher.debug("Submitting form via AJAX.");
      fields = {};
      fieldCount = 0;
      i = 0;
      $(inputSelector, this.form).each(function(input, i) {
        var attributeName, _ref;
        input = $(input);
        if (input[0].nodeName === "BUTTON" || (input[0].nodeName === "INPUT" && (input.attr("type").toLowerCase() === "submit" || input.attr("type").toLowerCase() === "button"))) {
          return;
        }
        if (input.fwData("forceSubmission") || (input.attr("type") && input.attr("type").toLowerCase() === "checkbox") || input.fwData('changed') || _this.options.submitUnchanged) {
          if (input.attr("type") !== "checkbox" || input.get(0).checked) {
            fieldCount++;
            attributeName = (_ref = input.attr("name")) != null ? _ref : "unnamedInput_" + i;
            return fields[attributeName] = input.val();
          }
        }
      });
      if (fieldCount === 0 && !this.options.submitFormIfAllUnchanged) {
        return setTimeout(function() {
          _this.enableForm();
          return _this.ajaxSuccess();
        }, 1);
      } else {
        return $.ajax({
          url: this.form.fwData("originalAction"),
          method: this.options.ajaxMethod,
          data: fields,
          type: "text",
          error: function(request) {
            return _this.callObservers("error", request.response);
          },
          success: function(request) {
            _this.enableForm();
            if (!_this.options.responseCheck(request.response)) {
              return _this.callObservers("error", request.response);
            } else {
              _this.callObservers("success", request.response);
              return _this.ajaxSuccess();
            }
          },
          complete: function(request) {
            _this.form.removeClass("submitting");
            return _this.callObservers("complete", request.response);
          }
        });
      }
    };

    Watcher.prototype.ajaxSuccess = function() {
      var element, elements, i, isEmpty, _i, _len, _ref, _results;
      _ref = this.allElements;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elements = _ref[_i];
        Formwatcher.unsetChanged(elements, this);
        if (this.options.resetFormAfterSubmit) {
          Formwatcher.restoreInitialValue(elements);
        } else {
          Formwatcher.storeInitialValue(elements);
        }
        isEmpty = elements.input.val() === null || !elements.input.val();
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (i in elements) {
            element = elements[i];
            if (isEmpty) {
              _results1.push(element.addClass("empty"));
            } else {
              _results1.push(element.removeClass("empty"));
            }
          }
          return _results1;
        })());
      }
      return _results;
    };

    return Watcher;

  })();

  module.exports = Watcher;

}).call(this);
