// Generated by CoffeeScript 1.3.3
(function() {
  var Formwatcher, Watcher, bean, bonzo, inputSelector, qwery, reqwest,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  Formwatcher = require("./formwatcher");

  bonzo = require("bonzo");

  qwery = require("qwery");

  reqwest = require("reqwest");

  bean = require("bean");

  inputSelector = "input, textarea, select, button";

  Watcher = (function() {

    function Watcher(form, options) {
      var Decorator, Validator, binput, element, elements, errorsElement, hiddenSubmitButtonElement, i, input, label, onchangeFunction, submitButtons, validateElementsFunction, validator, _fn, _fn1, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3, _ref4,
        _this = this;
      this.bonzoForm = typeof form === "string" ? bonzo(qwery(form)) : bonzo(form);
      if (this.bonzoForm.length < 1) {
        throw "Form element not found.";
      } else if (this.bonzoForm.length > 1) {
        throw "More than one form was found.";
      } else if (this.bonzoForm.get(0).nodeName !== "FORM") {
        throw "The element was not a form.";
      }
      this.form = this.bonzoForm.first();
      this.allElements = [];
      this.id = Formwatcher.currentWatcherId++;
      Formwatcher.add(this);
      this.observers = {};
      this.bonzoForm.fwData("watcher", this);
      this.bonzoForm.fwData("originalAction", this.bonzoForm.attr("action") || "").attr("action", "javascript:undefined;");
      this.options = Formwatcher.deepExtend({}, Formwatcher.defaultOptions, options || {});
      this.decorators = [];
      this.validators = [];
      _ref = Formwatcher.decorators;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        Decorator = _ref[_i];
        this.decorators.push(new Decorator(this));
      }
      _ref1 = Formwatcher.validators;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        Validator = _ref1[_j];
        this.validators.push(new Validator(this));
      }
      if (this.options.ajaxMethod === null) {
        this.options.ajaxMethod = (_ref2 = this.bonzoForm.attr("method")) != null ? _ref2.toLowerCase() : void 0;
      }
      switch (this.options.ajaxMethod) {
        case "post":
        case "put":
        case "delete":
          break;
        default:
          this.options.ajaxMethod = "get";
      }
      this.observe("submit", this.options.onSubmit);
      this.observe("success", this.options.onSuccess);
      this.observe("error", this.options.onError);
      this.observe("complete", this.options.onComplete);
      _ref3 = qwery(inputSelector, this.form);
      for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
        input = _ref3[_k];
        binput = bonzo(input);
        if (!binput.fwData("initialized")) {
          if (binput.attr("type") === "hidden") {
            binput.fwData("forceSubmission", true);
          } else {
            elements = Formwatcher.decorate(this, input);
            if (elements.input !== input) {
              bonzo(elements.input).attr("class", binput.attr("class"));
              input = elements.input;
              binput = bonzo(elements.input);
            }
            if (!elements.label) {
              label = Formwatcher.getLabel(elements, this.options.automatchLabel);
              if (label) {
                elements.label = label;
              }
            }
            if (!elements.errors) {
              errorsElement = Formwatcher.getErrorsElement(elements, true);
              elements.errors = errorsElement;
            }
            this.allElements.push(elements);
            binput.fwData("validators", []);
            _ref4 = this.validators;
            for (_l = 0, _len3 = _ref4.length; _l < _len3; _l++) {
              validator = _ref4[_l];
              if (validator.accepts(input, this)) {
                Formwatcher.debug("Validator '" + validator.name + "' found for input field '" + (binput.attr("name")) + "'.");
                binput.fwData("validators").push(validator);
              }
            }
            Formwatcher.storeInitialValue(elements);
            if (binput.val() === null || !binput.val()) {
              for (i in elements) {
                element = elements[i];
                bonzo(element).addClass("empty");
              }
            }
            if (!this.options.submitUnchanged) {
              Formwatcher.removeName(elements);
            }
            onchangeFunction = function() {
              return Formwatcher.changed(elements, _this);
            };
            validateElementsFunction = function() {
              return _this.validateElements(elements, true);
            };
            _fn = function(element) {
              var _this = this;
              bean.on(element, "focus", function() {
                return bonzo(element).addClass("focus");
              });
              bean.on(element, "blur", function() {
                return bonzo(element).removeClass("focus");
              });
              bean.on(element, "change", onchangeFunction);
              bean.on(element, "blur", onchangeFunction);
              return bean.on(element, "keyup", validateElementsFunction);
            };
            for (i in elements) {
              element = elements[i];
              _fn(element);
            }
          }
        }
      }
      submitButtons = qwery("input[type=submit], button[type=''], button[type='submit'], button:not([type])", this.form);
      hiddenSubmitButtonElement = bonzo.create('<input type="hidden" name="" value="" />')[0];
      this.bonzoForm.append(hiddenSubmitButtonElement);
      _fn1 = function(element) {
        var belement;
        belement = bonzo(element);
        return bean.on(element, "click", function(e) {
          var elementValue, tmpElementText, _ref5, _ref6;
          if (element.tagName === "BUTTON") {
            tmpElementText = belement.text();
            belement.text("");
            elementValue = (_ref5 = belement.val()) != null ? _ref5 : "";
            belement.text(tmpElementText);
          } else {
            elementValue = (_ref6 = belement.val()) != null ? _ref6 : "";
          }
          bonzo(hiddenSubmitButtonElement).attr("name", belement.attr("name") || "").val(elementValue);
          _this.submitForm();
          return e.stopPropagation();
        });
      };
      for (_m = 0, _len4 = submitButtons.length; _m < _len4; _m++) {
        element = submitButtons[_m];
        _fn1(element);
      }
    }

    Watcher.prototype.callObservers = function() {
      var args, eventName, observer, _i, _len, _ref, _results;
      eventName = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      _ref = this.observers[eventName];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        observer = _ref[_i];
        _results.push(observer.apply(this, args));
      }
      return _results;
    };

    Watcher.prototype.observe = function(eventName, func) {
      if (this.observers[eventName] === undefined) {
        this.observers[eventName] = [];
      }
      this.observers[eventName].push(func);
      return this;
    };

    Watcher.prototype.stopObserving = function(eventName, func) {
      var observer;
      this.observers[eventName] = (function() {
        var _i, _len, _ref, _results;
        _ref = this.observers[eventName];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          observer = _ref[_i];
          if (observer !== func) {
            _results.push(observer);
          }
        }
        return _results;
      }).call(this);
      return this;
    };

    Watcher.prototype.enableForm = function() {
      return bonzo(qwery(inputSelector, this.form)).removeAttr("disabled");
    };

    Watcher.prototype.disableForm = function() {
      return bonzo(qwery(inputSelector, this.form)).attr("disabled", "disabled");
    };

    Watcher.prototype.submitForm = function(e) {
      var _this = this;
      if (!this.options.validate || this.validateForm()) {
        this.callObservers("submit");
        this.bonzoForm.addClass("submitting");
        if (this.options.ajax) {
          this.disableForm();
          return this.submitAjax();
        } else {
          this.bonzoForm.attr("action", this.bonzoForm.fwData("originalAction"));
          setTimeout(function() {
            _this.form.submit();
            return _this.disableForm();
          }, 1);
          return false;
        }
      }
    };

    Watcher.prototype.validateForm = function() {
      var elements, validated, _i, _len, _ref;
      validated = true;
      _ref = this.allElements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elements = _ref[_i];
        if (!this.validateElements(elements)) {
          validated = false;
        }
      }
      return validated;
    };

    Watcher.prototype.validateElements = function(elements, inlineValidating) {
      var element, i, input, sanitizedValue, validated, validationOutput, validator, _i, _j, _len, _len1, _ref, _ref1;
      input = bonzo(elements.input);
      validated = true;
      if (input.fwData("validators").length) {
        if (!inlineValidating || !input.fwData("lastValidatedValue") || input.fwData("lastValidatedValue") !== input.val()) {
          input.fwData("lastValidatedValue", input.val());
          Formwatcher.debug("Validating input " + input.attr("name"));
          input.fwData("validationErrors", []);
          _ref = input.fwData("validators");
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            validator = _ref[_i];
            if (input.val() === "" && validator.name !== "Required") {
              Formwatcher.debug("Validating " + validator.name + ". Field was empty so continuing.");
              continue;
            }
            Formwatcher.debug("Validating " + validator.name);
            validationOutput = validator.validate(validator.sanitize(input.val()), input);
            if (validationOutput !== true) {
              validated = false;
              input.fwData("validationErrors").push(validationOutput);
              break;
            }
          }
          if (validated) {
            elements.errors.html("").hide();
            for (i in elements) {
              if (!__hasProp.call(elements, i)) continue;
              element = elements[i];
              bonzo(element).addClass("validated").removeClass("error");
            }
            if (inlineValidating) {
              elements.input.fwData("forceValidationOnChange", true);
            }
          } else {
            for (i in elements) {
              if (!__hasProp.call(elements, i)) continue;
              element = elements[i];
              bonzo(element).removeClass("validated");
            }
            if (!inlineValidating) {
              bonzo(elements.errors).html(input.fwData("validationErrors").join("<br />")).show();
              for (i in elements) {
                if (!__hasProp.call(elements, i)) continue;
                element = elements[i];
                bonzo(element).addClass("error");
              }
            }
          }
        }
        if (!inlineValidating && validated) {
          sanitizedValue = input.fwData("lastValidatedValue");
          _ref1 = input.fwData("validators");
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            validator = _ref1[_j];
            sanitizedValue = validator.sanitize(sanitizedValue);
          }
          input.val(sanitizedValue);
        }
      } else {
        for (i in elements) {
          if (!__hasProp.call(elements, i)) continue;
          element = elements[i];
          bonzo(element).addClass("validated");
        }
      }
      return validated;
    };

    Watcher.prototype.submitAjax = function() {
      var attributeName, fieldCount, fields, i, input, _i, _len, _ref, _ref1,
        _this = this;
      Formwatcher.debug("Submitting form via AJAX.");
      fields = {};
      fieldCount = 0;
      i = 0;
      _ref = qwery(inputSelector, this.form);
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        input = _ref[i];
        input = bonzo(input);
        if (input[0].nodeName === "BUTTON" || (input[0].nodeName === "INPUT" && (input.attr("type").toLowerCase() === "submit" || input.attr("type").toLowerCase() === "button"))) {
          return;
        }
        if (input.fwData("forceSubmission") || (input.attr("type") && input.attr("type").toLowerCase() === "checkbox") || input.fwData('changed') || this.options.submitUnchanged) {
          if (input.attr("type") !== "checkbox" || input.get(0).checked) {
            fieldCount++;
            attributeName = (_ref1 = input.attr("name")) != null ? _ref1 : "unnamedInput_" + i;
            fields[attributeName] = input.val();
          }
        }
      }
      if (fieldCount === 0 && !this.options.submitFormIfAllUnchanged) {
        return setTimeout(function() {
          _this.enableForm();
          return _this.ajaxSuccess();
        }, 1);
      } else {
        return reqwest({
          url: this.bonzoForm.fwData("originalAction"),
          method: this.options.ajaxMethod,
          data: fields,
          type: "text",
          error: function(request) {
            return _this.callObservers("error", request.response);
          },
          success: function(request) {
            _this.enableForm();
            if (!_this.options.responseCheck(request.response)) {
              return _this.callObservers("error", request.response);
            } else {
              _this.callObservers("success", request.response);
              return _this.ajaxSuccess();
            }
          },
          complete: function(request) {
            _this.bonzoForm.removeClass("submitting");
            return _this.callObservers("complete", request.response);
          }
        });
      }
    };

    Watcher.prototype.ajaxSuccess = function() {
      var element, elements, i, input, isEmpty, _i, _len, _ref, _results;
      _ref = this.allElements;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elements = _ref[_i];
        Formwatcher.unsetChanged(elements, this);
        if (this.options.resetFormAfterSubmit) {
          Formwatcher.restoreInitialValue(elements);
        } else {
          Formwatcher.storeInitialValue(elements);
        }
        input = bonzo(elements.input);
        isEmpty = input.val() === null || !input.val();
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (i in elements) {
            element = elements[i];
            element = bonzo(element);
            if (isEmpty) {
              _results1.push(element.addClass("empty"));
            } else {
              _results1.push(element.removeClass("empty"));
            }
          }
          return _results1;
        })());
      }
      return _results;
    };

    return Watcher;

  })();

  module.exports = Watcher;

}).call(this);
